In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
import nltk

In [2]:
from nltk.stem import PorterStemmer, WordNetLemmatizer

In [3]:
from nltk.corpus import stopwords

In [4]:
from nltk.tokenize import word_tokenize, sent_tokenize

In [5]:
import re

In [6]:
data = "Hello my name is Cristiano Ronaldo. Do you know me?"

In [7]:
nltk.download('movie_reviews')
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package movie_reviews to
[nltk_data]     C:\Users\rcc\AppData\Roaming\nltk_data...
[nltk_data]   Package movie_reviews is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\rcc\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\rcc\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\rcc\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\rcc\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [8]:
# doc = [
#     "Football is the sport played in ground",
#     "Players playing football should have great physics",    
# ]

In [9]:
def lower(doc):
    return doc.lower()

def punc(doc):
    new = re.sub(r'[^\w\s]', "", doc)
    new = re.sub(r'https?://s+', "", doc)
    return new

def token(doc):
    return word_tokenize(doc)

def stop(doc):
    sw = set(stopwords.words('english'))
    rs = [ i for i in doc if i not in sw ]
    return rs

def stem(doc):
    st = PorterStemmer()
    gs = [ st.stem(i) for i in doc]
    return gs

In [10]:
def preprocess_text(doc):
    l = lower(doc)
    p = punc(l)
    t = token(p)
    stp = stop(t)
    stm = stem(stp)
    return " ".join(stm)

In [11]:
doc = "My name is Cristiano Ronaldo. I loved to played cricke!!!!, we loved to played football as well"

In [12]:
preprocess_text(doc)

'name cristiano ronaldo . love play crick ! ! ! ! , love play footbal well'

In [13]:
from nltk.corpus import movie_reviews
data = [
    (movie_reviews.raw(fileid), category) 
    for category in movie_reviews.categories() 
    for fileid in movie_reviews.fileids(category)
]

documents, labels = [data[i][0] for i in range(len(data))], [data[i][1] for i in range(len(data))]
df=pd.DataFrame()
df["review"]=documents
df["label"]=labels
df

                                                 review label
0     plot : two teen couples go to a church party ,...   neg
1     the happy bastard's quick movie review \ndamn ...   neg
2     it is movies like these that make a jaded movi...   neg
3      " quest for camelot " is warner bros . ' firs...   neg
4     synopsis : a mentally unstable man undergoing ...   neg
...                                                 ...   ...
1995  wow ! what a movie . \nit's everything a movie...   pos
1996  richard gere can be a commanding actor , but h...   pos
1997  glory--starring matthew broderick , denzel was...   pos
1998  steven spielberg's second epic film on world w...   pos
1999  truman ( " true-man " ) burbank is the perfect...   pos

[2000 rows x 2 columns]

In [14]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['labels'] = le.fit_transform(df['label'])
df

                                                 review label  labels
0     plot : two teen couples go to a church party ,...   neg       0
1     the happy bastard's quick movie review \ndamn ...   neg       0
2     it is movies like these that make a jaded movi...   neg       0
3      " quest for camelot " is warner bros . ' firs...   neg       0
4     synopsis : a mentally unstable man undergoing ...   neg       0
...                                                 ...   ...     ...
1995  wow ! what a movie . \nit's everything a movie...   pos       1
1996  richard gere can be a commanding actor , but h...   pos       1
1997  glory--starring matthew broderick , denzel was...   pos       1
1998  steven spielberg's second epic film on world w...   pos       1
1999  truman ( " true-man " ) burbank is the perfect...   pos       1

[2000 rows x 3 columns]

In [15]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

vectorizer = TfidfVectorizer()
x = vectorizer.fit_transform(df['review'])
print(vectorizer.get_feature_names_out())

['00' '000' '0009f' ... 'zwigoff' 'zycie' 'zzzzzzz']

In [16]:
X_train, X_test, y_train, y_test = train_test_split(x, df.labels, test_size=0.2)

LGE = LogisticRegression()
model = LGE.fit(X_train,y_train)

In [17]:
prediction = model.predict(X_test)
prediction

array([1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 1])

In [18]:
report = classification_report(prediction,y_test)
print(report)

              precision    recall  f1-score   support

           0       0.81      0.82      0.81       203
           1       0.81      0.80      0.81       197

    accuracy                           0.81       400
   macro avg       0.81      0.81      0.81       400
weighted avg       0.81      0.81      0.81       400